#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 12 17:05:37 2017

@author: Petersiw
"""
import pandas as pd
from pandas import notnull
import os
import numpy as np

def corr(directory, threshold = 0):
    #read files from directory
    files_list = os.listdir(directory)
    d1 = pd.DataFrame()
    d2 = pd.DataFrame()
    for fle in files_list:
        d1 = (pd.DataFrame(pd.read_csv(fle)))
        d1 = d1[["sulfate", "nitrate"]]
        a = d1.notnull().sum().min()
        #remove rows with NA
        d1 = d1[d1.notnull()]
        #compute correlation if available observations meets threshold
        if (a > threshold):
            cor = d1.corr().iloc[0, 1]
        else:
            cor = np.NAN
        b = pd.Series(cor, index = [int(str(fle)[:3])])
        d2 = pd.concat((d2, b))
    #sort according to index
    d2 = d2.sort_index()
    #rename columns
    d2.columns = ["correlation"]
    d2.index.rename("ID", inplace = True)
    #remove NAs
    d2 = d2.dropna()
    return d2

#data obtained from https://d396qusza40orc.cloudfront.net/rprog%2Fdata%2Fspecdata.zip
corr("/Users/Petersiw/Desktop/specdata", 100)

