#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 12 17:50:49 2017

@author: Petersiw
"""

import pandas as pd
from pandas import notnull
import os
import numpy as np

def polt_mean(directory, pollutant):
    #read files from directory
    files_list = os.listdir(directory)
    data = pd.DataFrame()
    for fle in files_list:
        d1 = (pd.DataFrame(pd.read_csv(fle)))
        data = pd.concat([data, d1])
    if (pollutant == "sulfate"):
        data_sub = data["sulfate"]
    else:
        data_sub = data["nitrate"]
    return data_sub.dropna().mean()
    
#data obtained from https://d396qusza40orc.cloudfront.net/rprog%2Fdata%2Fspecdata.zip

polt_mean("/Users/Petersiw/Desktop/specdata", "sulfate")