#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 12 15:29:09 2017

@author: Petersiw
"""

import pandas as pd
from pandas import notnull
import os

def complete (directory):
    #read files from directory
    files_list = os.listdir(directory)
    d2 = pd.DataFrame()
    for fle in files_list:
        #read individual files
        data = (pd.DataFrame(pd.read_csv(fle)))
        data = data[["ID", "sulfate", "nitrate"]]
        #number of observations without missing data
        a = data.notnull().sum().min()
        fle1 = int(str(fle)[:3])
        b = pd.Series(a, index = [fle1])
        d2 = pd.concat([d2, b], axis = 0)
    #sort according to index
    d2 = d2.sort_index()
    #rename columns
    d2.columns = ["nobs"]
    d2.index.rename("ID", inplace = True)
    return d2

#data obtained from https://d396qusza40orc.cloudfront.net/rprog%2Fdata%2Fspecdata.zip

dat = complete("/Users/Petersiw/Desktop/specdata")
dat